# A minimal left prompt
format = """$character"""

# move the rest of the prompt to the right
right_format = """$all"""

# Inserts a blank line between shell prompts
#add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
#[character]                            # The name of the module we are configuring is "character"
# success_symbol = "[➜  ](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[hostname]
ssh_only = false
format =  "@[$hostname](bold red) "
#trim_at = ".companyname.com"
disabled = false

# <===>
[aws]
symbol = "  "
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'

[conda]
symbol = " "

[dart]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[directory]
read_only = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'

[elm]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[git_branch]
symbol = " "
format = '\[[$symbol$branch]($style)\]'

[golang]
symbol = " "

[hg_branch]
symbol = " "
format = '\[[$symbol$branch]($style)\]'

[java]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[julia]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[kotlin]
format = '\[[$symbol($version)]($style)\]'

[kubernetes]
format = '\[[$symbol$context( \($namespace\))]($style)\]'

[memory_usage]
symbol = " "

[nim]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[nix_shell]
symbol = " "
format = '\[[$symbol$state( \($name\))]($style)\]'

#[package]
#symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "

